language: cpp
compiler: gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-dev

script:
  - cd extlib/sparsehash && ./configure && make && sudo make install && cd ../..
  - cd extlib/CGAL && mkdir -p build/release && cd build/release cmake -DCMAKE_BUILD_TYPE=Release ../.. && sudo make && cd ../../../..
  - mkdir build && cd build && cmake .. && sudo make && cd ..
