language: cpp
compiler: gcc

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-dev

script:
  - cwd=$(pwd) && extlib/sparsehash && ./configure && make && sudo make install && cd cwd
  - cwd=$(pwd) && cd extlib/cgal && mkdir -p build/release && cd build/release cmake -DCMAKE_BUILD_TYPE=Release ../.. && sudo make && cd cwd
  - cwd=$(pwd) && mkdir build && cd build && cmake .. && sudo make && cd cwd
